# Generated by Django 2.2.5 on 2019-09-07 18:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=200, unique=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteModel',
            fields=[
                ('id', models.CharField(max_length=300, primary_key=True, serialize=False)),
                ('id_client', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=300)),
                ('price', models.IntegerField()),
                ('image', models.CharField(max_length=300)),
                ('brand', models.CharField(max_length=300)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now, max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='UserModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('username', models.CharField(max_length=60, unique=True)),
                ('first_name', models.CharField(max_length=40)),
                ('last_name', models.CharField(max_length=40)),
                ('email', models.EmailField(max_length=300, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now)),
                ('token', models.CharField(default='-- -- --', max_length=300)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
